# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/redmi/rosemary-miuicamera/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter camellia,$(TARGET_DEVICE)),)

endif
